AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  quarkus functions

Globals:
  Function:
    Timeout: 20
    MemorySize: 256
    Architectures:
      - x86_64
    Environment:
      Variables:
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

Resources:
  # quarkus JDK
  ## 256
  ### Fibonacci
  FibonacciFunctionQuarkus256:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FibonacciFunctionQuarkus256
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      Policies: AWSLambdaBasicExecutionRole
      AutoPublishAlias: snap
      SnapStart:
        ApplyOn: PublishedVersions
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL: rnd.serverless.impl.fibonacci.Fibonacci
    Metadata:
      BuildMethod: makefile
  ### RSA
  RSAFunctionQuarkus256:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RSAFunctionQuarkus256
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      Policies: AWSLambdaBasicExecutionRole
      AutoPublishAlias: snap
      SnapStart:
        ApplyOn: PublishedVersions
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL: rnd.serverless.impl.rsa.RSA
    Metadata:
      BuildMethod: makefile
  ### Factorial
  FactorialFunctionQuarkus256:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FactorialFunctionQuarkus256
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      Policies: AWSLambdaBasicExecutionRole
      AutoPublishAlias: snap
      SnapStart:
        ApplyOn: PublishedVersions
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL: rnd.serverless.impl.factorial.Factorial
    Metadata:
      BuildMethod: makefile
  ## 512
  ### Fibonacci
  FibonacciFunctionQuarkus512:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FibonacciFunctionQuarkus512
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      Policies: AWSLambdaBasicExecutionRole
      AutoPublishAlias: snap
      SnapStart:
        ApplyOn: PublishedVersions
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL: rnd.serverless.impl.fibonacci.Fibonacci
      MemorySize: 512
    Metadata:
      BuildMethod: makefile
  ### RSA
  RSAFunctionQuarkus512:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RSAFunctionQuarkus512
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      Policies: AWSLambdaBasicExecutionRole
      AutoPublishAlias: snap
      SnapStart:
        ApplyOn: PublishedVersions
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL:
            rnd.serverless.impl.rsa.RSA
      MemorySize: 512
    Metadata:
      BuildMethod: makefile
  ### Factorial
  FactorialFunctionQuarkus512:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FactorialFunctionQuarkus512
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      Policies: AWSLambdaBasicExecutionRole
      AutoPublishAlias: snap
      SnapStart:
        ApplyOn: PublishedVersions
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL: rnd.serverless.impl.factorial.Factorial
      MemorySize: 512
    Metadata:
      BuildMethod: makefile
  # quarkus native
  ## 256
  ### Fibonacci
  FibonacciFunctionQuarkusNative256:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FibonacciFunctionQuarkusNative256
      Handler: not.used.in.provided.runtime
      Runtime: provided
      Policies: AWSLambdaBasicExecutionRole
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL: rnd.serverless.impl.fibonacci.Fibonacci
    Metadata:
      BuildMethod: makefile
  ### RSA
  RSAFunctionQuarkusNative256:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RSAFunctionQuarkusNative256
      Handler: not.used.in.provided.runtime
      Runtime: provided
      Policies: AWSLambdaBasicExecutionRole
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL: rnd.serverless.impl.rsa.RSA
    Metadata:
      BuildMethod: makefile
  ### Factorial
  FactorialFunctionQuarkusNative256:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FactorialFunctionQuarkusNative256
      Handler: not.used.in.provided.runtime
      Runtime: provided
      Policies: AWSLambdaBasicExecutionRole
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL: rnd.serverless.impl.factorial.Factorial
    Metadata:
      BuildMethod: makefile
  ## 512
  ### Fibonacci
  FibonacciFunctionQuarkusNative512:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FibonacciFunctionQuarkusNative512
      Handler: not.used.in.provided.runtime
      Runtime: provided
      Policies: AWSLambdaBasicExecutionRole
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL: rnd.serverless.impl.fibonacci.Fibonacci
      MemorySize: 512
    Metadata:
      BuildMethod: makefile
  ### RSA
  RSAFunctionQuarkusNative512:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RSAFunctionQuarkusNative512
      Handler: not.used.in.provided.runtime
      Runtime: provided
      Policies: AWSLambdaBasicExecutionRole
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL: rnd.serverless.impl.rsa.RSA
      MemorySize: 512
    Metadata:
      BuildMethod: makefile
  ### Factorial
  FactorialFunctionQuarkusNative512:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FactorialFunctionQuarkusNative512
      Handler: not.used.in.provided.runtime
      Runtime: provided
      Policies: AWSLambdaBasicExecutionRole
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL: rnd.serverless.impl.factorial.Factorial
      MemorySize: 512
    Metadata:
      BuildMethod: makefile
