AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  spring functions

Globals:
  Function:
    Timeout: 20
    MemorySize: 256
    Architectures:
      - x86_64
    Environment:
      Variables:
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

Resources:
  # Spring JDK
  ## 256
  ### Fibonacci
  FibonacciFunctionSpringNative256:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FibonacciFunctionSpringNative256
      Handler: no.handler.required
      Runtime: provided.al2
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL: rnd.serverless.impl.fibonacci.Fibonacci
    Metadata:
      BuildMethod: makefile
  ### RSA
  RSAFunctionSpringNative256:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RSAFunctionSpringNative256
      Handler: no.handler.required
      Runtime: provided.al2
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL: rnd.serverless.impl.rsa.RSA
    Metadata:
      BuildMethod: makefile
  ### Factorial
  FactorialFunctionSpringNative256:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FactorialFunctionSpringNative256
      Handler: no.handler.required
      Runtime: provided.al2
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL: rnd.serverless.impl.factorial.Factorial
    Metadata:
      BuildMethod: makefile
  ## 512
  ### Fibonacci
  FibonacciFunctionSpringNative512:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FibonacciFunctionSpringNative512
      Handler: no.handler.required
      Runtime: provided.al2
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL: rnd.serverless.impl.fibonacci.Fibonacci
      MemorySize: 512
    Metadata:
      BuildMethod: makefile
  ### RSA
  RSAFunctionSpringNative512:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RSAFunctionSpringNative512
      Handler: no.handler.required
      Runtime: provided.al2
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL: rnd.serverless.impl.rsa.RSA
      MemorySize: 512
    Metadata:
      BuildMethod: makefile
  ### Factorial
  FactorialFunctionSpringNative512:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FactorialFunctionSpringNative512
      Handler: no.handler.required
      Runtime: provided.al2
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          IMPL: rnd.serverless.impl.factorial.Factorial
      MemorySize: 512
    Metadata:
      BuildMethod: makefile