version = 0.1
[default.build.parameters]
build_image = ["al2-graalvm:micronaut"]
use_container = true
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "micronaut-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3ufuwfjah2zd"
s3_prefix = "micronaut-app"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
